travis:
  secure:
    BINSTAR_TOKEN: QLAth8IlcCU0WkSI13PkZajdumQq1YYd7jH2qg+VsYNgKFrAac9Q41sS2Iswv83OBFHdnQ4AhFv+gE58iNUR9UMzYmeMGIqu3KjZpebFYY+Si/umjJn22xqEUfdHZRkcTc5tPXsiAOG5SqmEiXKiim1428CwPyOTZjjg/13fdvSc/Ih7eNq5i7G+dYm3p7MixQ/J2upo9Ns91a1YKHzxS+I/mG5fXweN8uAnIlT6LlB2IUKNpgaVjOdT7XFe4PpLbZ33E2mFeIksmgfGBTY86C1cFWv/rD8tUjYgERyQTXxZctlmJFha/84d8Q/gXWPjZkPPLthAw+6C64dYn0wcF5FOZzNbHXW8HSABj3d2DYkZ84QRN/hhi2my8kSOyBjajJ0qI/qnMS6+083QOl5PvmKj9KlODlywVmALvZ2/G9NUqzQsY4eFKvBT4ebC+3grQAcUYDJM5fj9cyiW1V9Er0Wry0RelEvFk4rxNOXueU2GuqF5hyuLxwn31a27IbbMfBcsSwCdbxrzy7FaVjSsmF7GQWiFfOpB02x7gTUxjj1qEzY/orUMpQMKItktO7yegfSqzUmwkjfjegnC7byIxFc4p8h/51asQNunKs/zXGKve6WERD9ooNDmktgI3DPtVG6z0XZqNrNmV3aS67bDpdD2F6UP3RgXUtZSPnoZ6Kk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
