travis:
  secure:
    BINSTAR_TOKEN: sTeakQ+kBRP61wcLyv6XEREi+yfN0w3VVxaghGOdek8LA7Dw6XMPjhCQ6Uf6GlQYAkUChRaKI0/E5Qo+HwmPcWCuP0jMwavZ4D82JZDoDGXKtUAd7mH64vinXSN5CW+fHbw1jI6oj98jJ4l+V6DbVi2QNDz7oQTMT8rk5nvsE+/5V/n6rf54Oe69rvGa4OlI5S3f1ugY+kZugkbiCLDqnk6bWkxcJfrQJY2coolBkcfjsWug2t/6w7lEP6HjjTTE+JHy6ZCU6UoaAlTkR1WgTPSiOFXqmlaISiN123oHyilL4Okh2dYykG3ndgX/LJxC4x2IT1D7OckE1zz8FPqeG5KwTqOnNCrNt8aO9iH+VnB1h/VUgGZGuUII18US699RZQKuDtOPiFpUfhdAewP8wU9VpyPsBUyPpPQLq+uZQh/ABtNq00sFHLEMuLQdOdyGdywEDEQ8rHnw088Y15O0PXo5ph5bKS6R2bQg3+IIVbK0dmyEbVot9ocpCE8fN7BFGRjTpjjWIXDH4fxi7RbO68jmlcPMUrhw5ji6jAIFR61ZkUuG8BuaV6udNsDDh1y2N1hkcj6W+L2plIEHiwDc1oTWl24xAYBHld+DMyGbmKMHpJaxwLJg6+SeTA5iTmZDwI7bCHQPP+lqyacxZJRkkaOVXK3xkowIbWscQxnq2PI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
